package com.dabomstew.pkrandom.hac.unity;

import java.util.HashMap;
import java.util.Map;

public class CommonString {
    public static Map<Integer,String> strings = setupStrings();

    private static Map<Integer,String> setupStrings() {
        Map<Integer,String> map = new HashMap<>();
        map.put(0,"AABB");
        map.put(5,"AnimationClip");
        map.put(19,"AnimationCurve");
        map.put(34,"AnimationState");
        map.put(49,"Array");
        map.put(55,"Base");
        map.put(60,"BitField");
        map.put(69,"bitset");
        map.put(76,"bool");
        map.put(81,"char");
        map.put(86,"ColorRGBA");
        map.put(96,"Component");
        map.put(106,"data");
        map.put(111,"deque");
        map.put(117,"double");
        map.put(124,"dynamic_array");
        map.put(138,"FastPropertyName");
        map.put(155,"first");
        map.put(161,"float");
        map.put(167,"Font");
        map.put(172,"GameObject");
        map.put(183,"Generic Mono");
        map.put(196,"GradientNEW");
        map.put(208,"GUID");
        map.put(213,"GUIStyle");
        map.put(222,"int");
        map.put(226,"list");
        map.put(231,"long long");
        map.put(241,"map");
        map.put(245,"Matrix4x4f");
        map.put(256,"MdFour");
        map.put(263,"MonoBehaviour");
        map.put(277,"MonoScript");
        map.put(288,"m_ByteSize");
        map.put(299,"m_Curve");
        map.put(307,"m_EditorClassIdentifier");
        map.put(331,"m_EditorHideFlags");
        map.put(349,"m_Enabled");
        map.put(359,"m_ExtensionPtr");
        map.put(374,"m_GameObject");
        map.put(387,"m_Index");
        map.put(395,"m_IsArray");
        map.put(405,"m_IsStatic");
        map.put(416,"m_MetaFlag");
        map.put(427,"m_Name");
        map.put(434,"m_ObjectHideFlags");
        map.put(452,"m_PrefabInternal");
        map.put(469,"m_PrefabParentObject");
        map.put(490,"m_Script");
        map.put(499,"m_StaticEditorFlags");
        map.put(519,"m_Type");
        map.put(526,"m_Version");
        map.put(536,"Object");
        map.put(543,"pair");
        map.put(548,"PPtr<Component>");
        map.put(564,"PPtr<GameObject>");
        map.put(581,"PPtr<Material>");
        map.put(596,"PPtr<MonoBehaviour>");
        map.put(616,"PPtr<MonoScript>");
        map.put(633,"PPtr<Object>");
        map.put(646,"PPtr<Prefab>");
        map.put(659,"PPtr<Sprite>");
        map.put(672,"PPtr<TextAsset>");
        map.put(688,"PPtr<Texture>");
        map.put(702,"PPtr<Texture2D>");
        map.put(718,"PPtr<Transform>");
        map.put(734,"Prefab");
        map.put(741,"Quaternionf");
        map.put(753,"Rectf");
        map.put(759,"RectInt");
        map.put(767,"RectOffset");
        map.put(778,"second");
        map.put(785,"set");
        map.put(789,"short");
        map.put(795,"size");
        map.put(800,"SInt16");
        map.put(807,"SInt32");
        map.put(814,"SInt64");
        map.put(821,"SInt8");
        map.put(827,"staticvector");
        map.put(840,"string");
        map.put(847,"TextAsset");
        map.put(857,"TextMesh");
        map.put(866,"Texture");
        map.put(874,"Texture2D");
        map.put(884,"Transform");
        map.put(894,"TypelessData");
        map.put(907,"UInt16");
        map.put(914,"UInt32");
        map.put(921,"UInt64");
        map.put(928,"UInt8");
        map.put(934,"unsigned int");
        map.put(947,"unsigned long long");
        map.put(966,"unsigned short");
        map.put(981,"vector");
        map.put(988,"Vector2f");
        map.put(997,"Vector3f");
        map.put(1006,"Vector4f");
        map.put(1015,"m_ScriptingClassIdentifier");
        map.put(1042,"Gradient");
        map.put(1051,"Type*");
        map.put(1057,"int2_storage");
        map.put(1070,"int3_storage");
        map.put(1083,"BoundsInt");
        map.put(1093,"m_CorrespondingSourceObject");
        map.put(1121,"m_PrefabInstance");
        map.put(1138,"m_PrefabAsset");
        map.put(1152,"FileSize");

        return map;
    }
}
